#!/bin/sh /etc/rc.common

START=99

start() {
    rm -f /data/.ugreen_nas/conf/ssh_tag
    for num in $(seq 1 5); do
        if [ "$(pgrep -c nas_svr)" -gt 0 ]; then
            if [ "$(netstat -lnpt | grep -c 9996)" -gt 0 ]; then
                break
            fi
        fi
        sleep 2
    done
    echo "root:123456" | chpasswd -m
    /etc/sshd restart
}
